# Generated by Django 2.0.1 on 2018-01-15 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freegeek', '0003_roster'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerTaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('hours_multiplier', models.DecimalField(decimal_places=3, max_digits=10)),
                ('instantiable', models.BooleanField()),
                ('lock_version', models.IntegerField()),
                ('effective_on', models.DateTimeField(blank=True, null=True)),
                ('ineffective_on', models.DateTimeField(blank=True, null=True)),
                ('adoption_credit', models.NullBooleanField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='freegeek.Program')),
            ],
            options={
                'db_table': 'volunteer_task_types',
            },
        ),
    ]
