# Generated by Django 2.0.1 on 2018-01-15 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freegeek', '0003_roster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('lock_version', models.IntegerField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('date_performed', models.DateField(blank=True, null=True)),
                ('community_service_type_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='freegeek.Program')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('volunteer_task_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.VolunteerTaskType')),
            ],
            options={
                'db_table': 'volunteer_tasks',
            },
        ),
    ]
