# Generated by Django 2.0.1 on 2018-01-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_volunteertask'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerDefaultEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(blank=True, max_length=1, null=True)),
                ('weekday_id', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'volunteer_default_events',
            },
        ),
    ]
