# Generated by Django 2.0.1 on 2018-01-15 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_volunteerdefaultevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('nowalkins', models.BooleanField()),
                ('volunteer_default_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.VolunteerDefaultEvent')),
            ],
            options={
                'db_table': 'volunteer_events',
            },
        ),
    ]
