# Generated by Django 2.0.1 on 2018-01-15 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freegeek', '0003_roster'),
        ('scheduling', '0004_volunteerevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerDefaultShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('slot_count', models.IntegerField(blank=True, null=True)),
                ('class_credit', models.NullBooleanField()),
                ('not_numbered', models.BooleanField()),
                ('stuck_to_assignment', models.BooleanField()),
                ('effective_on', models.DateField(blank=True, null=True)),
                ('ineffective_on', models.DateField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='freegeek.Program')),
                ('roster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='freegeek.Roster')),
                ('volunteer_default_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.VolunteerDefaultEvent')),
                ('volunteer_task_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.VolunteerTaskType')),
            ],
            options={
                'db_table': 'volunteer_default_shifts',
            },
        ),
    ]
