# Generated by Django 2.0.1 on 2018-01-15 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freegeek', '0003_roster'),
        ('scheduling', '0007_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelled', models.NullBooleanField()),
            ],
            options={
                'db_table': 'attendance_types',
            },
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='attendance_type_id',
        ),
        migrations.RemoveField(
            model_name='volunteertask',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='contact',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='freegeek.Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='attendance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.AttendanceType'),
        ),
    ]
