# Generated by Django 2.0.1 on 2018-01-15 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_auto_20180115_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'call_status_types',
            },
        ),
        migrations.CreateModel(
            name='CommunityServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('hours_multiplier', models.FloatField()),
                ('lock_version', models.IntegerField()),
            ],
            options={
                'db_table': 'community_service_types',
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_open', models.NullBooleanField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
            options={
                'db_table': 'weekdays',
            },
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='call_status_type_id',
        ),
        migrations.RemoveField(
            model_name='volunteerdefaultevent',
            name='weekday_id',
        ),
        migrations.RemoveField(
            model_name='volunteertask',
            name='community_service_type_id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='call_status_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.CallStatusType'),
        ),
        migrations.AddField(
            model_name='volunteerdefaultevent',
            name='weekday',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.Weekday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='community_service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.CommunityServiceType'),
        ),
    ]
