# Generated by Django 2.0.1 on 2018-01-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('volunteer', models.BooleanField()),
                ('adoption_credit', models.BooleanField()),
            ],
            options={
                'db_table': 'programs',
            },
        ),
    ]
