# Generated by Django 2.0.1 on 2018-01-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freegeek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organization', models.NullBooleanField()),
                ('sort_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=25, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_address', models.CharField(blank=True, max_length=52, null=True)),
                ('address', models.CharField(blank=True, max_length=52, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state_or_province', models.CharField(blank=True, max_length=15, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=25, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lock_version', models.IntegerField()),
                ('next_milestone', models.IntegerField(blank=True, null=True)),
                ('contract_id', models.IntegerField()),
                ('fully_covered', models.NullBooleanField()),
                ('birthday', models.DateField(blank=True, null=True)),
                ('volunteer_intern_title', models.CharField(blank=True, max_length=255, null=True)),
                ('next_monthly_milestone', models.IntegerField(blank=True, null=True)),
                ('exported_to_sf', models.DateTimeField(blank=True, null=True)),
                ('household', models.IntegerField(blank=True, null=True)),
                ('addr_rejected', models.NullBooleanField()),
                ('addr_certified', models.BooleanField()),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
