# Generated by Django 2.0.1 on 2018-01-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freegeek', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField()),
                ('limit_shift_signup_by_program', models.BooleanField()),
                ('contact_type_id', models.IntegerField(blank=True, null=True)),
                ('restrict_to_every_n_days', models.IntegerField(blank=True, null=True)),
                ('restrict_from_sked_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rosters',
            },
        ),
    ]
