# Generated by Django 2.0.1 on 2018-01-14 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freegeek', '0003_roster'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('lock_version', models.IntegerField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('community_service_type_id', models.IntegerField(blank=True, null=True)),
                ('date_performed', models.DateField(blank=True, null=True)),
                ('program_id', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'volunteer_tasks',
            },
        ),
        migrations.CreateModel(
            name='VolunteerTaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('hours_multiplier', models.DecimalField(decimal_places=3, max_digits=10)),
                ('instantiable', models.BooleanField()),
                ('lock_version', models.IntegerField()),
                ('effective_on', models.DateTimeField(blank=True, null=True)),
                ('ineffective_on', models.DateTimeField(blank=True, null=True)),
                ('adoption_credit', models.NullBooleanField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='freegeek.Program')),
            ],
            options={
                'db_table': 'volunteer_task_types',
            },
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='volunteer_task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='freegeek.VolunteerTaskType'),
        ),
    ]
